name: MD5
description: MD5 hash
inputs:
  path:
    description: File path
    required: true
outputs:
  digest:
    description: MD5 hex digest
    value: ${{ steps.md5.outputs.version-changed }}
runs:
  using: composite
  steps:
    - id: md5
      shell: bash
      run: |
        digest=$(md5sum ${{ inputs.path }} | cut -d ' ' -f 1)
        echo $digest
        echo digest=$digest >> "$GITHUB_OUTPUT"
